### ISSUE TITLE
set_keepalive returns err “unread data in buffer”

### ISSUE THREAD

**Issue by legdonkey** [ledgetech/lua-resty-http#137] opened 2018-01-17 06:56 UTC
i have a odd issue,i use res:read_body to read all the response body,then use set_keepalive.but its returns error  “unread data in buffer”.
I try to use res:read_trailers() after res:read_body,but it seams does not work.

**Comment by danielBreitlauch** [comment] 2018-03-09 12:07
Same for me.

**Comment by shuoqingding** [comment] 2018-03-22 05:36
same here

**Comment by danielBreitlauch** [comment] 2018-03-23 09:55
Actually for me the issue is resolved. It was showing this bc connections with timeouts where kept alive instead of closed.
After closing every connection that had a timeout the buffers were fine.

**Comment by sshniro** [comment] 2020-04-15 08:15
Same here.

**Comment by VeryCrazyDog** [comment] 2020-04-20 07:56
Same here, but I found in my case, it is because the server return the value of HTTP header `Content-Length` is smaller than the actual content length, and I resolve this by closing the connection when `set_keepalive` fails.

**Comment by pintsized** [comment] 2020-04-20 15:03
Yes, if you have unread data still on the wire then something seems incorrect with that response (bad `Content-Length` for example), or you stopped reading prematurely for some other reason. The connection will be in a state which is not safe to reuse.

**Comment by Roycohen** [comment] 2020-12-09 11:41
Hi There,

I've found an issue when the returned result is null with content length of 4.
It is easy to reproduce. Seems like the body is not detected properly and then the keepalive fails because there is still data on the wire..
Can someone help in this?

**Comment by pintsized** [comment] 2020-12-09 21:16
Sure, are you able to post a minimal example that would demonstrate the problem?

**Closed** 2022-12-15 10:24 UTC
