### ISSUE TITLE
Connection Pool not working

### ISSUE THREAD

**Issue by Roycohen** [ledgetech/lua-resty-http#160] opened 2018-10-04 16:00 UTC
Hi There,

I'm using the request_uri method with connection pool options as shown bellow but when I use the get_reused_times method I always get an error "Closed".

I'm 99% sure that this is not working for me therefore there is a high load on the servers.
Also another Q, is whether I need to use the set_keepalive method when using the request_uri method.
I tried with and without set_keepalive but I always get an error from the get_reused_times method.

Code
	local http = require "resty.http"
	local hc = http:new()
	local times, errReusedTimes = hc:get_reused_times()
	if errReusedTimes then
		trace("times err: " .. tostring(errReusedTimes or ""))
	end

        local url = "http://sometest.com"
	trace("times: " .. tostring(times or ""))
	local timeout =5000
	hc:set_timeout(timeout)
	local res, err = hc:request_uri(url, {
		keepalive_timeout = 60,
		keepalive_pool = 10,
		ssl_verify = false,
		method = "HEAD",
		version = 1.1
	})

	hc:set_keepalive(60000, "test")

**Comment by hamishforbes** [comment] 2018-10-05 09:14
1) You're calling `get_reused_times` before a connection has been made, you have to make a connection to know if its been reused.
2) You're manually calling `set_keepalive` with a pool size of `"test"`, that's  not going to work
3) The `request_uri` method already sets the keepalive so the manual call is superfluous anyway
4) The `keepalive_timeout` param is in ms, so you're only keeping connections in the pool for 60ms

Most likely you're not seeing connection reuse because of the last point. 
You should either use the `request` interface (not `request_uri`) or set the `keepalive_timeout` param correctly.

**Comment by Roycohen** [comment] 2018-10-06 08:51
Hi @hamishforbes,

Thanks for the quick reply.
I've set the timeout to 60000 and removed the manual `set_keepalive`.
I've also used the `get_reused_times` after the HTTP request( `request_uri`) and it still doesn't work.
I get "closed" error from the `get_reused_times` method.

Imagine that the variables are set.
`
	local http = require "resty.http"
	local hc = http:new()
	local timeout = tonumber(timeout or 5000)
	hc:set_timeout(timeout)
        local url = "http://sometest.com"
	local res, err = hc:request_uri(url, {
		keepalive_timeout = 60000,
		keepalive_pool = 10,
		ssl_verify = false,
		method = "HEAD",
		version = 1.1
	})

	local code, body, headers
	body = ""
	headers = {}
	if res then
		code = res.status
		body = res.body
		headers = res.headers
	end

	if err then
		ngx.say("Request failed")
		ngx.say(err)
		return body, headers
	end

	ngx.say("Server reply code: " .. code)
	if code ~= 200 then
		ngx.say("Server Code != 200")
	else
		ngx.say('Server reply: ' .. body)
		dump(headers)
	end
	local times, errReusedTimes = hc:get_reused_times()
	if errReusedTimes then
		ngx.say("times err: " .. tostring(errReusedTimes or ""))
	end
	ngx.say("times: " .. tostring(times or ""))
`

This can be easily tested.

**Comment by Roycohen** [comment] 2018-10-07 15:58
Another thing that I've noted, is that even when I use the `request` method and not `request_uri` after the connection is being made it goes to TIME_WAIT status.
I can't understand why.

This is my code:
`
	local host = "www.google.com"
	local port = 80
	local path = "/"
	local query = ""
	local method = "HEAD"

	local http = require "resty.http"
	local hc = http:new()
	local timeout = 5000
	hc:set_timeout(timeout)
	local ok, err = hc:connect(host, port, {pool = "http_pool"})
	if port == 443 then
		local session, err = hc:ssl_handshake(nil, host, false)
		if err then
			ngx.say("SSL Handhsake error: " .. tostring(err or ""))
			ngx.exit()
		end

		ngx.say("session: " .. tostring(session or ""))
	end

	if err then
		ngx.say(err)
		ngx.exit()
	end

	local headers = {
		["Connection"] = "Keep-Alive",
		["User-Agent"] = ngx.var.http_user_agent
	}

	local res, err = hc:request({
		ssl_verify = false,
		method = method,
		path = path,
		query = query,
		headers = headers,
		version = 1.1
	})


	local code, body, headers
	body = ""
	headers = {}
	if res then
		code = res.status
		headers = res.headers
	end

	if err then
		ngx.say("Request failed")
		ngx.say(err)
		return body, headers
	end

	local times, errReusedTimes = hc:get_reused_times()
	if errReusedTimes then
		ngx.say("times reused err: " .. tostring(errReusedTimes or ""))
	else
		ngx.say("times reused: " .. tostring(times or ""))
	end

	ngx.say("Server reply code: " .. code)
	if code ~= 200 then
		ngx.say("Server Code != 200")
		hc:close()
	else
		if res.has_body then
			local err
			body, err = res:read_body()
			if err then
				ngx.say("Failed to read body")
			end
		end

		local ok, keepaliveErr = hc:set_keepalive(60000, 1)
		if keepaliveErr then
			ngx.say("keepaliveErr: " .. tostring(keepaliveErr or ""))
		end
		ngx.say("keepalive : " .. tostring(ok or ""))
	end
`

This is what I get always:
times reused: 0
Server reply code: 200

So the reused time is always 0
and in netstat I always see another connection in TIME_WAIT state.

I don't understand why.
Any help will be really appreciated.

**Comment by Roycohen** [comment] 2018-10-09 07:33
@hamishforbes, @pintsized, can you please assist?

**Comment by pintsized** [comment] 2018-10-10 15:54
I'm afraid I don't have time to look into your specific case, but there are tests here which confirm the keepalive pool works as expected. Perhaps reviewing this will shed some light: https://github.com/pintsized/lua-resty-http/blob/master/t/07-keepalive.t

**Comment by oasfuyou** [comment] 2019-03-26 10:28
when i read the words below:

-- The server said we must close the connection, so we cannot setkeepalive.
        -- If close() succeeds we return 2 instead of 1, to differentiate between
        -- a normal setkeepalive() failure and an intentional close().

if when the local res, err=sock:setkeepalive(...),if the res=1,means setkeepalive failed????

**Comment by taotao2014** [comment] 2020-06-11 15:40
+1

**Comment by NICK-DUAN** [comment] 2020-11-24 12:32
Is this problem still here? Any solutions?

**Comment by pintsized** [comment] 2020-11-26 16:37
Just to clarify for anyone new coming here; as far as I'm aware, there are no known issues with the keepalive implementation.

If you are not getting connection reuse as expected, it is most likely something specific to do with your connections. Please keep in mind that this module is widely used in production in high traffic environments.

This being said, of course there is always the chance of bugs, here or even behavioural changes in the stack upon which this module depends. If someone can provide a minimal reproducible failing test against a known end point (say httpbin or similar) then we can start to figure it out.

All I have so far is anecdotal complaints of things not working in user-specific scenarios, which I can't debug.

To be clear, I'm not shutting this down or declaring "there are no bugs"! Merely stating that as of right now, I'm not aware of any actual bugs with regards to keepalive.

**Comment by NICK-DUAN** [comment] 2020-11-27 08:38
@pintsized could you give a example to us?

**Comment by pintsized** [comment] 2020-11-27 08:53
How about adding a failing test case here to demonstrate the problem? https://github.com/ledgetech/lua-resty-http/blob/master/t/07-keepalive.t

**Comment by szl-926929** [comment] 2020-12-18 09:43
i found if rebuild httpc，connection can't be reuse. and the case of  https://github.com/ledgetech/lua-resty-http/blob/master/t/07-keepalive.t, httpc not rebuild。

**Comment by szl-926929** [comment] 2020-12-18 09:45
I have the same problem。and not sure how to solve it

**Comment by szl-926929** [comment] 2020-12-18 09:46
@pintsized maybe, you can test

**Comment by pintsized** [comment] 2020-12-18 10:31
When you say "rebuild httpc" do you perhaps mean "reinstantiate", e.g: `local httpc = http.new()` for a second time?

Again, please post simple reproducible code examples so that I can help you! It's really difficult for me to guess what your problem might be.

Every time you call `http.new()`, you get a TCP socket connection object. If you call `get_reused_times` on this, it will be 0, because at this point it is just a new object. When you call `connect` on this object, the keepalive options will affect whether the pool will be consulted, and therefore whether a previously kept-alive underlying connection will be reused or not.

I think perhaps some folks are having problems here because our documentation has not been kept up to date with the core `lua-nginx-module` documentation. I'll try to fix this up soon. Please note that we simply proxy our calls onto the relevant cosocket calls, and so I highly recommend reading those docs thoroughly.

https://github.com/openresty/lua-nginx-module/#ngxsockettcp

In particular, pay attention to the deprecation of the pool size in `setkeepalive` and the options table for `connect`.

Also, please note that the keepalive pool is *per worker*, and not per server. So if you have, say, four nginx worker processes, you will have four connection pools and your outbound connections will be split between them. Please be aware of this when testing, as naturally your results may vary.

For now, I'm all out of guesses! Please post a reproducible test case that demonstrates your problem if you still suspect there is a bug.

**Comment by pintsized** [comment] 2021-03-04 10:24
Closing this in lieu of anything that looks like a bug. Remember, if you use `request_uri` instead of connecting manually then the connection will be closed or placed back on the connection pool. Calling `get_reused_times` on a closed connection doesn't make any sense.

**Closed by pintsized** 2021-03-04 10:24 UTC
